### ISSUE TITLE
Unable to mock WarcraftClient

### ISSUE THREAD

**Issue by Bwolfing** [danjagnow/ArgentPonyWarcraftClient#50]
First of all, nice work! I was trying to work on something similar, but this solution seems much nicer!

### Description
Unfortunately the implementation doesn't support mocking, at the very least with the use of the [Moq](https://www.nuget.org/packages/Moq/) library. Without support for mocking, individuals won't be able to write unit tests for their code when they use this library, which may limit adoption.

```
Failed   If_Request_Is_Successful_Then_Guild_Name_Is_Returned
Error Message:
 System.NotSupportedException : Invalid setup on a non-virtual (overridable in VB) member: c => c.GetCharacterAsync(It.IsAny<String>(), It.IsAny<String>(), It.IsAny<CharacterFields>())
Stack Trace:
   at Moq.Mock.ThrowIfSetupExpressionInvolvesUnsupportedMember(Expression setup, MethodInfo method) in C:\projects\moq4\Source\Mock.cs:line 954
   at Moq.Mock.SetupPexProtected[T,TResult](Mock`1 mock, Expression`1 expression, Condition condition) in C:\projects\moq4\Source\Mock.cs:line 543
   at Moq.Mock.Setup[T,TResult](Mock`1 mock, Expression`1 expression, Condition condition) in C:\projects\moq4\Source\Mock.cs:line 526
   at ArgentPonyTest.Test.<If_Request_Is_Successful_Then_Guild_Name_Is_Returned>d__3.MoveNext() in C:\Projects\Scratchpad\ArgentPonyTest\ArgentPonyTest\Test.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\AsyncInvocationRegion.cs:line 113
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context) in C:\src\nunit\nunit\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 96
```

### Steps to reproduce
I created a minimal example of the issue [here](https://github.com/Bwolfing/ArgentPonyMockingFailure).

### Possible Solutions
- One option, which would be the simpler approach, is to change all methods to virtual. However this may be less than ideal because someone could inherit from the `WarcraftClient` and override those methods. Granted, that puts the error on the implementer, but the possibility exists.
- Create simple interfaces which represent the methods on the `WarcraftClient` such as
```
public interface IWarcraftClient
{
    Task<RequestResult<Character>> GetCharacterAsync(string realm, string characterName, CharacterFields fields = CharacterFields.None);
}

public class WarcraftClient : IWarcraftClient
{
    // Existing code
}
```
This may be a better solution for 2 reasons:
1. Interfaces are well supported by Moq meaning it solves the initial problem
2. Mocking an interface doesn't require using the class's constructor.
    - What I mean by that is mentioned in this [SO answer](https://stackoverflow.com/a/35994668/5884242); if you're mocking the client, it's helpful to only need to mock the interface instead of the class itself.

I am happy to take on fixing this task, and would opt for implementing the second solution.

**Comment by TravisBoatman** [comment]
This would be good to have. Using an interface would be the best way of doing this. Go ahead and create a `IWarcraftClient` interface.

**Comment by danjagnow** [comment]
Agreed.  Adding an `IWarcraftClient` interface is a good idea.
